### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/slopes#18]
The aim of testing code is to determine that it is '[fit for use](https://en.wikipedia.org/wiki/Unit_testing)'.

The key thing that should be tested in this package, I think, are whether the slopes returned are 'correct'. Key to that assessment is having a 'ground truth' of data with correct slopes. I think the test dataset with slopes from ArcMap provides a good starting point, but wonder if there is a more definitive way to testing that the slopes are right? 

May be worth looking at old papers on slope calculation. 

From the perspective of rOpenSci, there are clear recommendations:

- [ ] All packages should have a test suite that covers major functionality of the package. The tests should also cover the behavior of the package in case of errors.

- [ ] It is good practice to write unit tests for all functions, and all package code in general, ensuring key functionality is covered. Test coverage below 75% will likely require additional tests or explanation before being sent for review.

- [ ] We recommend using testthat for writing tests. Strive to write tests as you write each new function. This serves the obvious need to have proper testing for the package, but allows you to think about various ways in which a function can fail, and to defensively code against those. More information.

**Comment by Robinlovelace** [comment]
Exciting update, after the commit above, we're now on 5%, 70 more percentage points to go!

![image](https://user-images.githubusercontent.com/1825120/98607904-fcd90880-22e1-11eb-971a-a6c8c3528ed0.png)

**Comment by layik** [comment]
👍

**Comment by mpadge** [comment]
Hiya folk, I saw the thread on [rOpenSci submission](https://github.com/ropensci/software-review/issues/420#issuecomment-775310953). In case it helps, I've got an example of using secrets on github actions [here](https://github.com/ropenscilabs/pkgreport/blob/master/.github/workflows/gitlab.yaml#L29) - you should pretty much be able to copy that general approach to get a private MAPBOX token into your test environment.

**Comment by Robinlovelace** [comment]
Finally taking a looking at this.

**Comment by Robinlovelace** [comment]
Heads-up @mpadge I think the commits above fixed the issue. Issue now is that `sf` does not work on Mac, e.g. as shown here: https://github.com/ITSLeeds/slopes/runs/2143877715?check_suite_focus=true

Any ideas how to fix that? Seems that any package with an `sf` dependency will fail on actions...

**Comment by Robinlovelace** [comment]
E.g.: failing tests on osmdata https://github.com/ropensci/osmdata/runs/2139987665

**Comment by mpadge** [comment]
Yeah, `sf` is current broken on lots of systems. @edzer and @rsbivand have sent quite a few tweets about it, all related to the epic `spatstat` restructure. All are working with CRAN to fix everything asap.

**Comment by Robinlovelace** [comment]
And all may be fixed when Mac binaries are rebuilt hopefully.

**Comment by mpadge** [comment]
Timetable for full alignment in on main [`spatstat` page](https://github.com/baddstats/spatstat). Most packages currently failing (including nearly all of mine) have a grace period until end of March to either auto-align with new system, or to submit updates. March 25th is key date when all on CRAN should be fixed; before then i wouldn't worry too much.

**Comment by temospena** [comment]
The test coverage is still (a bit) low.

```r
> covr::package_coverage()
slopes Coverage: 59.35%
R/slope_get.R: 0.00%
R/plot_slope.R: 28.57%
R/data.R: 66.67%
R/palette.R: 66.67%
R/elevation.R: 78.02%
R/slopes.R: 86.44%
```

**Comment by temospena** [comment]
A few new tests to bump up the coverage:

1. For `R/slope_get.R`: Since this file doesn't actually depend on `ceramic` (it relies on standard `terra` functionality and matrices), we could write a complete test suite for it. That alone should push `R/slope_get.R` to 100% coverage.
2. For `R/plot_slope.R`: The reason it wasn't being evaluated by `covr` was that the existing test skipped graphics output entirely unless the user was running R interactively (using `skip_if_not(interactive())`), which `covr` doesn't do. I added a new test block that temporarily captures the plot to a dummy PDF (`pdf(file = tempfile())`), and executes the `plot_slope` and `plot_dz` functions cleanly behind the scenes.

```text
slopes Coverage: 84.43%
R/data.R: 66.67%
R/elevation.R: 78.02%
R/slopes.R: 86.44%
R/plot_slope.R: 87.14%
R/palette.R: 100.00%
R/slope_get.R: 100.00%
```

What improved:
* **`R/slope_get.R`**: Jumped from 0% to **100%**.
* **`R/plot_slope.R`**: Jumped from 28.57% to **87.14%**.
* **`R/palette.R`**: Jumped from 66.67% to **100%**. 
* **overall slopes coverage**: Jumped from 59.35% to **84.43%**

The remaining uncovered bits are mostly in `elevation.R` and `slopes.R`, which rely on the `ceramic` package downloading elevation data from a remote API.
